# Generated by Django 4.2.1 on 2023-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
