# Generated by Django 4.2.1 on 2023-06-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('available', 'Available'), ('sold', 'Sold')], default='available', max_length=50)),
                ('code', models.BigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='product_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_via_bot', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='categories.category')),
            ],
        ),
    ]
