# Generated by Django 4.2.1 on 2023-06-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_out',
            field=models.BooleanField(default=False),
        ),
    ]
